#define OPER_EQU                        1
#define OPER_AND                        2
#define OPER_OR                         3
#define OPER_CMP                        4
#define OPER_NEQ                        5
#define OPER_GTH                        6
#define OPER_GTE                        7
#define OPER_LTH                        8
#define OPER_LTE                        9
#define OPER_ADD                       10
#define OPER_SUB                       11
#define OPER_DIV                       12
#define OPER_MUL                       13
#define OPER_MOD                       14
#define OPER_POW                       15
#define OPER_NOT                       16
