#define OPERATOR_EQU                    1
#define OPERATOR_AND                    2
#define OPERATOR_OR                     3
#define OPERATOR_CMP                    4
#define OPERATOR_NEQ                    5
#define OPERATOR_GTH                    6
#define OPERATOR_GTE                    7
#define OPERATOR_LTH                    8
#define OPERATOR_LTE                    9
#define OPERATOR_ADD                   10
#define OPERATOR_SUB                   11
#define OPERATOR_DIV                   12
#define OPERATOR_MUL                   13
#define OPERATOR_MOD                   14
#define OPERATOR_NOT                   15
#define OPERATOR_SEMI_COLON            16
#define TOKEN_TYPE_IDENTIFIER          17
#define TOKEN_TYPE_VARIABLE            18
#define OPERATOR_OPEN_PAREN            19
#define OPERATOR_CLOSE_PAREN           20
