#define OPERATOR_EQU                    1
#define OPERATOR_AND                    2
#define OPERATOR_OR                     3
#define OPERATOR_CMP                    4
#define OPERATOR_NEQ                    5
#define OPERATOR_GTH                    6
#define OPERATOR_GTE                    7
#define OPERATOR_LTH                    8
#define OPERATOR_LTE                    9
#define OPERATOR_ADD                   10
#define OPERATOR_SUB                   11
#define OPERATOR_DIV                   12
#define OPERATOR_MUL                   13
#define OPERATOR_MOD                   14
#define OPERATOR_NOT                   15
#define KEYWORD_FUNCTION               16
#define TOKEN_TYPE_VARIABLE            17
#define OPERATOR_OPEN_PAREN            18
#define OPERATOR_CLOSE_PAREN           19
#define KEYWORD_ENDFUNCTION            20
#define OPERATOR_SEMI_COLON            21
#define OPERATOR_OBJECT_REF            22
#define TOKEN_TYPE_INTEGER             23
#define TOKEN_TYPE_STRING              24
#define TOKEN_TYPE_ARGUMENT            25
#define TOKEN_TYPE_FLOAT               26
#define OPERATOR_COMMA                 27
#define KEYWORD_ELIF                   28
#define KEYWORD_ELSE                   29
#define KEYWORD_ENDIF                  30
#define KEYWORD_IF                     31
#define KEYWORD_WHILE                  32
#define KEYWORD_ENDWHILE               33
#define KEYWORD_VAR                    34
#define KEYWORD_RETURN                 35
